"""init

Revision ID: 39b141e69075
Revises: 
Create Date: 2026-05-23 19:50:06.618274
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '39b141e69075'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('era', sa.Text(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('古遗址', '古墓葬', '古建筑', '石窟寺及石刻', '近现代重要史迹及代表性建筑', '其他')", name='pois_category_check'),
    sa.CheckConstraint('batch BETWEEN 1 AND 8', name='pois_batch_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.execute(
        "ALTER TABLE pois ADD COLUMN has_extended boolean "
        "GENERATED ALWAYS AS (COALESCE(array_length(image_urls,1),0) > 0 OR website IS NOT NULL) STORED"
    )
    op.create_index('pois_batch_idx', 'pois', ['batch'], unique=False)
    op.create_index('pois_category_idx', 'pois', ['category'], unique=False)
    op.create_index('pois_geom_gix', 'pois', ['location'], unique=False, postgresql_using='gist')
    op.create_index('pois_name_trgm', 'pois', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('pois_province_idx', 'pois', ['province'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','user')", name='users_role_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('api_keys_user_id_idx', 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('api_keys_user_id_idx', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index('pois_province_idx', table_name='pois')
    op.drop_index('pois_name_trgm', table_name='pois', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('pois_geom_gix', table_name='pois', postgresql_using='gist')
    op.drop_index('pois_category_idx', table_name='pois')
    op.drop_index('pois_batch_idx', table_name='pois')
    op.drop_table('pois')
    # ### end Alembic commands ###
